#!/bin/sh
set -eu
while read -r local_ref local_oid remote_ref remote_oid; do
    case "$local_oid" in
        *[!0]*) python3 scripts/check-publication.py --revision "$local_oid" ;;
        *) continue ;; # Deleting a remote ref publishes no tree.
    esac
done
